credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: John Smith
      password: $2b$12$KJX8.VH8.i9mgwBrwIkisOE9Tvucaph13uItGoDfWzz17CLr7e5Qa
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Rebecca Briggs
      password: $2b$12$3coTvdySVbr4bVJNLPYYle3TPPM8p.ECkpRRjbsTemJWg9VP6UWLC
cookie:
  expiry_days: 1 #0.00694444444444
  key: cookie_key # Must be string
  name: authentication_cookie